name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate the version number
      run: |
           VERSION="1.0.${{github.run_number}}"
           echo "VERSION=$VERSION" >> GITHUB_ENV
           echo "Version: $VERSION"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dassudip2001/demoaoo:VERSION
    - name: List of docker images
      run: docker images
